### ISSUE TITLE
MATEROM - Bug report for the number of jobs

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#11]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/materom/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

**STEPS TO REPRODUCE:**

Open URL in browser
Type the name of the company (Materom) in the search bar
Click on the button "Cauta"
Click on the link below the company logo
Open the careers section 
Click on the button “Run scrapper”
See the number of jobs available underneath the graphic (28 jobs available)
Verify if the number of the jobs on https://scrapers.peviitor.ro/src/materom/index.html  is the  same as the number of the jobs on https://peviitor.ro/rezultate?q=materom&country=Rom%C3%A2nia&page=1  by clicking on the logo image of the company 

**EXPECTED RESULTS:**
The number of the jobs are the same on the both URL’s

**ACTUAL RESULTS:**
The jobs number (28 job offers) on https://scrapers.peviitor.ro/src/materom/index.html is different than the number of jobs (14 offers) on the https://peviitor.ro/rezultate?q=materom&country=Rom%C3%A2nia&page=1.  See atachaments.

![MATEROM- nr_joburi_2](https://github.com/peviitor-ro/scrapers_david/assets/129604131/e314c3f7-f4f6-49fa-a8df-1b597239c0da)
![MATEROM- nr_joburi_1](https://github.com/peviitor-ro/scrapers_david/assets/129604131/a565e3f3-4942-4969-b3d6-b3bd6da8e2ef)

**Comment by davidmondoc** [comment]
@DeedeeDL partially fixed sites bugs but still working on it. haven't check yet the issue about job number discrepancy

**Comment by DeedeeDL** [comment]
retested.pass.
