### ISSUE TITLE
CBS - the number of jobs graphic is not displayed

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#15]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: PC
OS: Windows 10

**STEPS TO REPRODUCE:**

Open the URL in the browser
Type "CBS" in the searching bar and enter.
Run scraper for "CBS" Company
Verify graphic where the jobs numbers are displayed.

**EXPECTED RESULTS:**
The graphic is displayed correctly where we can see the daily numbers of the jobs.

**ACTUAL RESULTS:**
The graphic doesn't show anything.

<img width="1214" alt="cbs - graphic bug" src="https://github.com/peviitor-ro/Scrapers-UI/assets/129604131/214caac7-63ac-46da-9304-ee53d7ebced6">

**Comment by lalalaurentiu** [comment]
@davidmondoc numele scraperului trebuie sa fie la fel ca numele companiei, nu sunt acceptate spatii in numele firmelor
![Screenshot 2024-01-29 at 12 11 37](https://github.com/peviitor-ro/scrapers_david/assets/67306273/8eaeac5f-332f-4bb0-baf8-e1bce14479b5)

**Comment by davidmondoc** [comment]
I've updated the company name file as should have been from he beginning. please retest

- am actualizat numele în fișier, poți **retesta** mâine

**Comment by DeedeeDL** [comment]
Retested.OK
