### ISSUE TITLE
TMAX - "Careers" and "Targetare" link don't work

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#20]
ENVIROMENT: production
COMPANY: Tmax
URL: https://scrapers.peviitor.ro/src/tmax/index.html#
Browser: Google Chrome
Device: PC
OS: Windows10

**Precondition:**
The site https://scrapers.peviitor.ro/ must be open with google chrome .
Typing TMAX in the search bar.

**Steps:**
Open https://scrapers.peviitor.ro/
Enter Tmax in the search bar. Enter
Click the link with the name of the company.
Open the page with TMAX
Verify in  box where the "Careers" and "Targetare" are displayed if these 2 links are working properly

**Expected result:**
If we click on "Careers" and "Targetare" links everything goes well and we are redirected properly.

**Actual result:**
"Careers" and "Targetare" links don't work at all, we are not redirected anywhere.

<img width="230" alt="TMAX- links not working" src="https://github.com/peviitor-ro/scrapers_david/assets/129604131/d3f104b1-bea7-44f6-b6d2-c8dc6bfcdd2b">

**Comment by davidmondoc** [comment]
please retest after website update

**Comment by DeedeeDL** [comment]
Retested.Pass
