### ISSUE TITLE
TMAX - logo cannot be seen clearly because it is white and the background is light

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#28]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar and click Enter
Verify  if the logo is displayed well.

EXPECTED RESULTS:
The logo should be displayed properly.

ACTUAL RESULTS:
The logo is difficult to see because it is white on a light background
![IMG_3902](https://github.com/peviitor-ro/scrapers_david/assets/129604131/414edce5-c987-49ce-a62c-6956448314bb)

**Comment by davidmondoc** [comment]
@DeedeeDL please retest after update

**Comment by DeedeeDL** [comment]
@davidmondoc  still on the light background on firme.peviitor.to

![tmax](https://github.com/peviitor-ro/scrapers_david/assets/129604131/aa033da8-27cb-4dc7-b25d-1d0f451ff988)

**Comment by DeedeeDL** [comment]
retested.passs
