### ISSUE TITLE
Aeroportul Satu Mare- Data Base Error

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#32]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type "Aeropotul Satu Mare" in the search bar
3) Click Enter
4) Click on the button "Run Scraper"
5)Verify the status section above the button "Run Scraper".

**EXPECTED RESULTS:**
After click on the "Run scraper" button, the status is "Active"

**ACTUAL RESULTS:**
After click on the button "Run Scrapper" it the "Status" section appears "Database error" and it opens a window with a syntax error. See photo attached with this bug.

![Image](https://github.com/peviitor-ro/scrapers_david/assets/129604131/0da88d4d-6c1d-4075-adbf-69e41b8ebcf9)

**Comment by lalalaurentiu** [comment]
@davidmondoc 
![Screenshot 2024-02-17 at 21 17 01 (2)](https://github.com/peviitor-ro/scrapers_david/assets/67306273/04b49381-3670-4281-a266-ea363702f738)

**Comment by davidmondoc** [comment]
Am schimbat numele la toate scraperele mele

**Comment by davidmondoc** [comment]
Urmează să fac push. Încerc să rezolv mai multe înainte de push

**Comment by lalalaurentiu** [comment]
@davidmondoc ce sa zic baiat harnic :))

**Comment by davidmondoc** [comment]
Cred ca o sa fie cel mai mare push pe care l-am facut eu pana acum

**Comment by davidmondoc** [comment]
@DeedeeDL please retest

**Comment by DeedeeDL** [comment]
@davidmondoc still fail

**Comment by DeedeeDL** [comment]
done
