### ISSUE TITLE
Edu Kiwi - incorrect logo

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#51]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type the name of the company in the search bar
3) Click on the button "Cauta"
4) Check the logo of the company

EXPECTED RESULTS:
The logo of the company is well displayed.

ACTUAL RESULTS:
The other's company logo is displayed (from Eduboom)
![incorect logo](https://github.com/peviitor-ro/scrapers_david/assets/129604131/9c86103b-bc16-48d9-80c4-fa5734edc726)

**Comment by davidmondoc** [comment]
please retest after update

**Comment by DeedeeDL** [comment]
retested. pass
