### ISSUE TITLE
Eduboom- incorrect logo displayed.

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#52]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type the name of the company in the search bar
3) Click on the button "Cauta"
4) Verify if the logo is well displayed.

EXPECTED RESULTS:
The logo of the company eduboom is displayed.

ACTUAL RESULTS:
It appears the logo of other company (edukiwi)
![eduboom-logo_incorrect](https://github.com/peviitor-ro/scrapers_david/assets/129604131/df4ecb0f-22c7-4f58-88ef-e68431cb937a)

**Comment by davidmondoc** [comment]
please retest after update

**Comment by DeedeeDL** [comment]
retested. Pass
