### ISSUE TITLE
BUG REPORT for location of the job

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/scrapers_david#7]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/continentalhotels/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Type the name of the company in the search bar
3) Click on the button "Cauta"
4) Click on the link below the company logo
5) Open the careers section of the company website
6) Check the locations of the avalailable jobs

EXPECTED RESULTS:
The location of the jobs posted on the URL for the company should be the same like the location of the jobs posted on the company website on the career sections. The location should appears correctly.

ACTUAL RESULTS:
The location for the jobs : Camerista and Ospatar appears with an error like "Targu Mures is not a city in Romania" 

![dovada_bug_locatie](https://github.com/peviitor-ro/scrapers_david/assets/129604131/ba6b92bb-3e4c-43bb-8a5b-174c878b789b)

**Comment by davidmondoc** [comment]
@DeedeeDL am rezolvat bug-ul. te rog retesteaza. nu stiu de ce nu pot adauga label-ul FIXED

**Comment by DeedeeDL** [comment]
All good now ! Nu a mai aparut la retestare
